# Generated by Django 3.2.12 on 2022-04-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('ON_THE_WAY', 'ON_THE_WAY'), ('UNAVAILABLE', 'UNAVAILABLE'), ('ON_REPAIR', 'ON_REPAIR')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('ON_THE_WAY', 'ON_THE_WAY'), ('UNAVAILABLE', 'UNAVAILABLE')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('UNAVAILABLE', 'UNAVAILABLE'), ('CLOSED', 'CLOSED')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelManagement.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelManagement.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelManagement.route')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelManagement.city')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(to='travelManagement.Station'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelManagement.travel')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelManagement.place')),
            ],
        ),
    ]
