# Generated by Django 3.2.12 on 2022-04-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelManagement', '0003_auto_20220409_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='travel_id',
            new_name='travel',
        ),
    ]
