# Generated by Django 3.2.12 on 2022-04-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelManagement', '0004_rename_travel_id_place_travel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='place_id',
            new_name='place',
        ),
    ]
