DRIVER_CHOICES = (
    (
        "AVAILABLE",
        "AVAILABLE",
    ),
    ("ON_THE_WAY", "ON_THE_WAY"),
    ("UNAVAILABLE", "UNAVAILABLE"),
)
DRIVER_STATUSES = ("AVAILABLE", "UNAVAILABLE", "ON_THE_WAY")
ROUTE_CHOICES = (
    (
        "AVAILABLE",
        "AVAILABLE",
    ),
    ("UNAVAILABLE", "UNAVAILABLE"),
    ("CLOSED", "CLOSED"),
)
ROUTE_STATUSES = ("AVAILABLE", "UNAVAILABLE", "CLOSED")
BUS_CHOICES = (
    (
        "AVAILABLE",
        "AVAILABLE",
    ),
    ("ON_THE_WAY", "ON_THE_WAY"),
    ("UNAVAILABLE", "UNAVAILABLE"),
    ("ON_REPAIR", "ON_REPAIR"),
)
BUS_STATUSES = ("AVAILABLE", "UNAVAILABLE", "ON_THE_WAY", "ON_REPAIR")
